name: lotura
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 상태관리 라이브러리
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # JSON 파싱 라이브러리
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # 라우터
  go_router: ^14.8.1

  # Local DB
  shared_preferences: ^2.5.2

  # 이미지 svg
  flutter_svg: ^2.0.17

  # Icon
  material_symbols_icons: ^4.2808.1

  # Url Launcher
  url_launcher: ^6.3.1

  # Markdown
  flutter_markdown: ^0.7.6+2

  # HTTP
  dio: ^5.8.0+1

  # Socket
  web_socket_channel: ^3.0.2

  # DateFormat.. etc
  intl: ^0.20.2

  # Analyzer
  analyzer_plugin: ^0.13.1

  # Firebase
  firebase_core: ^3.15.0
  firebase_messaging: ^15.2.8

  # Local Notification
  flutter_local_notifications: ^19.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  flutter_lints: ^5.0.0

  # Generator
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.4

  # Modeling
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  source_gen: ^2.0.0

  # App Icon
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/image/banner/
    - assets/image/device/
    - assets/image/logo/
    - assets/icon/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/pretendard_semibold.ttf
          weight: 600
        - asset: assets/font/pretendard_medium.ttf
          weight: 500
        - asset: assets/font/pretendard_regular.ttf
          weight: 400

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
